### ISSUE TITLE
Flash support?

### ISSUE THREAD

**Issue by trex005** [postmanlabs/postman-chrome-interceptor#43]
I'm not sure if it is technically an XHR, but chrome's network tab intercepts communications flash makes.  Could interceptor also intercept these as well?

**Comment by kokole** [comment]
Any updates?

**Comment by MystK** [comment]
I'm also running into this. Any news?

**Comment by numaanashraf** [comment]
@trex005 @kokole @MystK Do you mean requests made via action script?

**Comment by kokole** [comment]
Yes.

**Comment by numaanashraf** [comment]
@kokole I'm afraid we cannot support this at the moment as Chrome doesn't give us programmatic access to the network layer of Flash runtimes. And given how Chrome is deprecating Flash slowly over the last couple of releases, we don't think Chrome would be adding support for this in the near future either.
