### ISSUE TITLE
How can I get things from HTTP response html using Javascript and then store it into environment?

### ISSUE THREAD

**Issue by komajunjun** [postmanlabs/postman-chrome-interceptor#48]

**Comment by madebysid** [comment]
@komajunjun You can get the response in the tests using the pre-defined variable `responseBody` (Optionally, run the sandbox function `xml2Json` on it to make parsing easier). You can then store it in an environment variable).

The Postman app's issue tracker is [here](https://github.com/postmanlabs/postman-app-support/issues). You can post further queries there.

**Comment by komajunjun** [comment]
@madebysid But the response data is not JSON format, it's HTML format. I can't parse responseBody to JSON object.

**Comment by madebysid** [comment]
@komajunjun The variable `responseBody` has the response body as a string. Running `xml2Json(responseBody)` will convert the XML into a JSON structure, which you can parse.

**Comment by komajunjun** [comment]
@madebysid THX
