### ISSUE TITLE
Response doesn't pick up correct language when Auto

### ISSUE THREAD

**Issue by akinom77** [postmanlabs/postman-chrome-interceptor#51]
Performing GET command, I get no results back other than **Unexpected '<'** if the output format is set as **Auto**. I need to manually change it to XML to see the result. Even if I save the settings then, the next time I run it, it defaults back to Auto. It should either work as default and detect language or allow me to save it as I wish to use it. 

I also have issues with input language, they all of a sudden all defaulted to text and I have to change them all manually to the correct one.

**Comment by madebysid** [comment]
Hi @akinom77, since this looks like a Postman App issue, can you create one [here](https://github.com/postmanlabs/postman-app-support/issues)? This helps us keep issues organized.
Can you also include what Content-Type your response contains?

**Comment by akinom77** [comment]
Will do. When I set content type at the headers section, as xml, it ignores it.
